#COPYDB-JOB.yaml
#Description
# This job is a one-off task to copy db files from container filesystem
# to a persistent volume externally.  Passing in COPYDBFROM and COPYDBTO
# to specify where db files to copy from/to, container will claim pvc2 
# and mount to /pv2 for holding db files.
#
apiVersion: batch/v1
kind: Job
metadata:
  name: copydb
spec:
  template:
    spec:
      containers:
      - name: apex19
        image: henryhhl18/apex19-container
        env:
        - name: COPYDBFROM
          value: "/u02"
        - name: COPYDBTO
          value: "/db"
        command: ["/bin/bash"]
        args: ["-c","cd $(COPYDBFROM);tar cf - * | ( cd $(COPYDBTO); tar xfp -)"]
        volumeMounts:
        - mountPath: /db
          name: storage-u02
      volumes:
        - name: storage-u02
          persistentVolumeClaim:
            claimName: pvc-apex19-db
      restartPolicy: Never
  backoffLimit: 1
